//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sourcelinkbug {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Xl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Xl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sourcelinkbug.Xl", typeof(Xl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area failed to start. Check the service log for details..
        /// </summary>
        internal static string AreaFailedToStart {
            get {
                return ResourceManager.GetString("AreaFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area failed to stop.  Killing service thread..
        /// </summary>
        internal static string AreaFailedToStop {
            get {
                return ResourceManager.GetString("AreaFailedToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area ID required..
        /// </summary>
        internal static string AreaIDRequired {
            get {
                return ResourceManager.GetString("AreaIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to set current version to an invalid type.
        /// </summary>
        internal static string AttemptToSetCurrentVersionToAnInvalidType {
            get {
                return ResourceManager.GetString("AttemptToSetCurrentVersionToAnInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Advantage version directory does not exist.
        /// </summary>
        internal static string BaseAdvantageVersionDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("BaseAdvantageVersionDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Command-Line Help{1}.
        /// </summary>
        internal static string CommandLineHelp1 {
            get {
                return ResourceManager.GetString("CommandLineHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Parameters:.
        /// </summary>
        internal static string CommonParameters {
            get {
                return ResourceManager.GetString("CommonParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file not found..
        /// </summary>
        internal static string ConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the application.  The application entry point assembly was not found for the specified application version: &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotStartTheApplicationApplicationEntryPointNotFound {
            get {
                return ResourceManager.GetString("CouldNotStartTheApplicationApplicationEntryPointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate &apos;{0}&apos; argument.
        /// </summary>
        internal static string Duplicate0Argument {
            get {
                return ResourceManager.GetString("Duplicate0Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate &apos;{0}&apos; argument &apos;{1}&apos;.
        /// </summary>
        internal static string Duplicate0Argument1 {
            get {
                return ResourceManager.GetString("Duplicate0Argument1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Error0 {
            get {
                return ResourceManager.GetString("Error0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t open command line argument file &apos;{0}&apos; : &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorCantOpenCommandLineArgumentFile01 {
            get {
                return ResourceManager.GetString("ErrorCantOpenCommandLineArgumentFile01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unbalanced &apos;\&quot;&apos; in command line argument file &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorUnbalancedInCommandLineArgumentFile0 {
            get {
                return ResourceManager.GetString("ErrorUnbalancedInCommandLineArgumentFile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start application..
        /// </summary>
        internal static string FailedToStartApplication {
            get {
                return ResourceManager.GetString("FailedToStartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid area ID: {0}.
        /// </summary>
        internal static string InvalidAreaID0 {
            get {
                return ResourceManager.GetString("InvalidAreaID0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version number..
        /// </summary>
        internal static string InvalidVersionNumber {
            get {
                return ResourceManager.GetString("InvalidVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid value for the &apos;{1}&apos; command line option.
        /// </summary>
        internal static string IsNotAValidValueForThe1CommandLineOption {
            get {
                return ResourceManager.GetString("IsNotAValidValueForThe1CommandLineOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid version folder..
        /// </summary>
        internal static string IsNotAValidVersionFolder {
            get {
                return ResourceManager.GetString("IsNotAValidVersionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing configuration value: CLIABV.
        /// </summary>
        internal static string MissingConfigurationValueCLIABV {
            get {
                return ResourceManager.GetString("MissingConfigurationValueCLIABV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required argument &apos;&lt;{0}&gt;&apos;..
        /// </summary>
        internal static string MissingRequiredArgument0 {
            get {
                return ResourceManager.GetString("MissingRequiredArgument0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required argument &apos;/{0}&apos;..
        /// </summary>
        internal static string MissingRequiredArgument0Alt1 {
            get {
                return ResourceManager.GetString("MissingRequiredArgument0Alt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is not a junction point..
        /// </summary>
        internal static string PathIsNotAJunctionPoint {
            get {
                return ResourceManager.GetString("PathIsNotAJunctionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue..
        /// </summary>
        internal static string PressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Successfully Stopped.
        /// </summary>
        internal static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Stopping.
        /// </summary>
        internal static string ServiceStopping {
            get {
                return ResourceManager.GetString("ServiceStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ADV_AREA_ID environment variable is already set to {0}.  Cannot use area {1}..
        /// </summary>
        internal static string TheADVAREAIDEnvironmentVariableIsAlreadySetTo0Cannot {
            get {
                return ResourceManager.GetString("TheADVAREAIDEnvironmentVariableIsAlreadySetTo0Cannot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application version folder does not exist: {0}.
        /// </summary>
        internal static string TheApplicationVersionFolderDoesNotExist0 {
            get {
                return ResourceManager.GetString("TheApplicationVersionFolderDoesNotExist0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete junction point..
        /// </summary>
        internal static string UnableToDeleteJunctionPoint {
            get {
                return ResourceManager.GetString("UnableToDeleteJunctionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine Advantage version.
        /// </summary>
        internal static string UnableToDetermineAdvantageVersion {
            get {
                return ResourceManager.GetString("UnableToDetermineAdvantageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine which Advantage area to use..
        /// </summary>
        internal static string UnableToDetermineWhichAdvantageAreaToUse {
            get {
                return ResourceManager.GetString("UnableToDetermineWhichAdvantageAreaToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the Advantage extensibility assembly: {0}.
        /// </summary>
        internal static string UnableToLoadTheAdvantageExtensibilityAssembly0 {
            get {
                return ResourceManager.GetString("UnableToLoadTheAdvantageExtensibilityAssembly0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve area settings for area &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToRetrieveAreaSettingsForArea0 {
            get {
                return ResourceManager.GetString("UnableToRetrieveAreaSettingsForArea0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized area: {0}..
        /// </summary>
        internal static string UnrecognizedArea0 {
            get {
                return ResourceManager.GetString("UnrecognizedArea0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized area ID in ADV_AREA_ID environment variable: {0}..
        /// </summary>
        internal static string UnrecognizedAreaIDInADVAREAIDEnvironmentVariable0 {
            get {
                return ResourceManager.GetString("UnrecognizedAreaIDInADVAREAIDEnvironmentVariable0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized command line argument &apos;{0}&apos;.
        /// </summary>
        internal static string UnrecognizedCommandLineArgument0 {
            get {
                return ResourceManager.GetString("UnrecognizedCommandLineArgument0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the /help option to see a list of available parameters..
        /// </summary>
        internal static string UseTheHelpOptionToSeeAListOfAvailableParameters {
            get {
                return ResourceManager.GetString("UseTheHelpOptionToSeeAListOfAvailableParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: No local version folder &apos;{0}&apos;.
        /// </summary>
        internal static string WarningNoLocalVersionFolder0 {
            get {
                return ResourceManager.GetString("WarningNoLocalVersionFolder0", resourceCulture);
            }
        }
    }
}
